CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(255) UNIQUE,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    EMAIL VARCHAR(300) UNIQUE,
    PWD VARCHAR(300),
    PHOTO VARCHAR(300),
    REGISTERED_AT TIMESTAMP
);

CREATE TABLE PROCESSES(
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL, 
    TITLE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT fk_proc_user FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE THREADS(
    ID SERIAL PRIMARY KEY,
    PROC_ID INT NOT NULL, 
    TITLE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_proc FOREIGN KEY(PROC_ID) REFERENCES PROCESSES(ID)
);

CREATE TABLE QUANTS(
    ID SERIAL PRIMARY KEY,
    THREAD_ID INT NOT NULL, 
    TITLE VARCHAR(255) NOT NULL,
    TEXT TEXT NOT NULL,
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_thread FOREIGN KEY(THREAD_ID) REFERENCES THREADS(ID)
);

CREATE UNIQUE INDEX proc_user_ids ON PROCESSES (USER_ID, TITLE);
CREATE UNIQUE INDEX thread_proc_ids ON THREADS (PROC_ID, TITLE);
CREATE UNIQUE INDEX quant_proc_ids ON QUANTS (THREAD_ID, TITLE);

CREATE TYPE CONTRIBUTES_TYPE AS ENUM(
    'create_process', 
    'create_thread', 
    'create_quant'
    );

CREATE TABLE CONTRIBUTIONS(
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    TYPE CONTRIBUTES_TYPE,
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_contr_user FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE SHEETS(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(300),
    PROC_ID INT NOT NULL,
    CONSTRAINT fk_sheets_proc FOREIGN KEY(PROC_ID) REFERENCES PROCESSES(ID)
);

CREATE UNIQUE INDEX sheets_proc_id_unique ON SHEETS (PROC_ID);

CREATE TABLE SHEETS_CONTENT(
    ID SERIAL PRIMARY KEY,
    SHEETS_ID INT NOT NULL,
    THEME VARCHAR(500),
    DATE DATE, 
    DONE BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_content_sheets FOREIGN KEY(SHEETS_ID) REFERENCES SHEETS(ID)
);


CREATE TABLE WORK_SESSIONS(
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    SHEET_CONTENT_ID INT NOT NULL,
    DT_START TIMESTAMP NOT NULL,
    DT_END TIMESTAMP,
    CONSTRAINT fk_worksession_user FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT fk_worksession_sheetcontent FOREIGN KEY(SHEET_CONTENT_ID) REFERENCES SHEETS_CONTENT(ID)
);


CREATE TABLE REPORTS(
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    TITLE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_reports_users FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);
CREATE UNIQUE INDEX reports_user_title ON REPORTS (USER_ID, TITLE);

CREATE TABLE REPORT_CONTENT(
    ID SERIAL PRIMARY KEY,
    REPORT_ID INT, 
    SC_ID INT,
    CONSTRAINT fk_rc_report FOREIGN KEY(REPORT_ID) REFERENCES REPORTS(ID),
    CONSTRAINT fk_rc_sc FOREIGN KEY(SC_ID) REFERENCES SHEETS_CONTENT(ID)
);