CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(255),
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    EMAIL VARCHAR(300),
    PWD VARCHAR(300),
    PHOTO VARCHAR(300),
    JWT VARCHAR(300),
    REGISTERED_AT TIMESTAMP
);

CREATE TABLE PROCESSES(
    ID SERIAL PRIMARY KEY,
    USER_ID INT, 
    TITLE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_proc_user FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE THREADS(
    ID SERIAL PRIMARY KEY,
    PROC_ID INT NOT NULL, 
    TITLE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_proc FOREIGN KEY(PROC_ID) REFERENCES PROCESSES(ID)
);

CREATE TABLE QUANTS(
    ID SERIAL PRIMARY KEY,
    THREAD_ID INT NOT NULL, 
    TITLE VARCHAR(255),
    TEXT TEXT,
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_thread FOREIGN KEY(THREAD_ID) REFERENCES THREADS(ID)
);

CREATE TYPE CONTRIBUTES_TYPE AS ENUM(
    'create_process', 
    'create_thread', 
    'create_quant'
    );

CREATE TABLE CONTRIBUTIONS(
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    TYPE CONTRIBUTES_TYPE,
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_contr_user FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);