CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(255),
    NAME VARCHAR(255),
    SURNAME VARCHAR(255)
);

CREATE TABLE PROCESSES(
    ID SERIAL PRIMARY KEY,
    USER_ID INT, 
    TITLE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE THREADS(
    ID SERIAL PRIMARY KEY,
    PROC_ID INT, 
    TITLE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_porc FOREIGN KEY(PROC_ID) REFERENCES PROCESSES(ID)
);

CREATE TABLE QUANTS(
    ID SERIAL PRIMARY KEY,
    THREAD_ID INT, 
    TITLE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    CONSTRAINT fk_thread FOREIGN KEY(THREAD_ID) REFERENCES THREADS(ID)
);
