version: '3.0'

services:
  db:
    image: 'postgres:15.2'
    container_name: 'pg_refl_proto'
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      #- "pg_metrics:/var/lib/postgresql/data"
      - "./migration/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_PASSWORD=${POSTGRES_PWD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
   # command: "psql -U {POSTGRES_USER} -p 5432 -f migrations/postgres_up"

# Predefined volumes
volumes:
  # Volume for postgres
  pg_metrics: